documentation-description
mattiaerre/purple-pluto pull request #6
Opened 2017-04-06 16:28 UTC by mariaathena

# description

add description and usage example to documentation

2017-04-06 16:29 UTC, mariaathena commented
will be fixed with #2

2017-04-07 01:11 UTC, mattiaerre requested changes
over to you @mariaathena please have a look at my notes 😉

2017-04-07 01:11 UTC, mattiaerre commented on README.md
> +- Mouse hoover
although I think this would be a really cool event to track, I believe there is a typo here 😅

2017-04-07 01:11 UTC, mattiaerre commented on README.md
> +- Scroll on page
clicks and scrolling events are not implemented yet, so I would only mention `mousemove` events for now

2017-04-07 01:11 UTC, mattiaerre commented on README.md
> +Todo: improve usage description
probably better to leave this section as a todo/wip for now

2017-04-07 01:11 UTC, mattiaerre commented on README.md
> +## Requirements
I like this `Requirements` section, let's expand it a bit

2017-04-07 21:57 UTC, mattiaerre commented on README.md
> +Todo: add usage description`
You missed a `'` 😅

2017-04-19 05:46 UTC, mattiaerre commented on README.md
> +Todo: add usage description`
@mariaathena if you fix this I will merge asap 👍

2017-04-19 09:05 UTC, mariaathena commented on README.md
> +Todo: add usage description`
my bad, all done!

2017-04-21 01:41 UTC, mattiaerre approved these changes
this LGTM

2017-04-21 01:41 UTC, merged